import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import { Toaster } from 'sonner'
import NProgressProvider from './context/Provider'
import { ThemeProvider } from './context/Theme'
import './globals.css'
import { isAuthenticated } from '@/lib/actions/auth'
import { redirect } from 'next/navigation'

const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const isUserAuthenticated = await isAuthenticated()

  if (!isUserAuthenticated) redirect('/sign-in')

  return (
    <html
      lang='en'
      className='light'
      suppressHydrationWarning
    >
      <body
        className={`${rubik.className} 
        antialiased inset-0 bg-neutral-50 dark:bg-neutral-950 
        bg-no-repeat bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(180,180,250,0.2),rgba(255,255,255,0))]  
        dark:bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(0,0,0,0))]'`}
        cz-shortcut-listen='true'
      >
        <NProgressProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
          >
            {children}
          </ThemeProvider>
        </NProgressProvider>
        <Toaster />
      </body>
    </html>
  )
}
